import React, { createContext, useContext, useState, useEffect } from 'react';
import { liveTranslationService } from '../services/liveTranslationService.js';

const LanguageContext = createContext();

export const translations = {
  en: {
    // App & Nav
    appName: 'Smriti Setu',
    tagline: 'Dementia & Cognitive Memory Care Intelligence',
    home: 'Home',
    scanner: 'Scanner',
    reportsRx: 'Reports & Rx',
    cabinet: 'My Cabinet',
    cognitiveGames: 'Memory Games',
    memoryReminders: 'Daily Reminders',
    caregiverAnalytics: 'Caregiver Hub',
    history: 'History',
    profile: 'Profile',
    logout: 'Logout',
    signIn: 'Sign in',
    signUp: 'Sign up',
    register: 'Register',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    alreadyAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    selectLanguage: 'Language',
    listenAudio: 'Listen (Audio)',
    speaking: 'Reading aloud...',
    voiceTherapist: 'Voice Therapist',
    voiceAI: 'Voice AI',

    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    dashboardSubtitle: "Here's a summary of your medicine scanning and health activity.",
    totalScans: 'Total Scans',
    allTimeScans: 'All time medicine analyses',
    lastScanDate: 'Last Scan Date',
    noRecentScans: 'No recent scans',
    latestDrug: 'Latest Medication',
    verifiedAI: 'AI Vision verified',
    scanNewMedicine: 'Scan New Medicine',
    scanNewDesc: 'Point camera at any medicine packaging for instant dosage, indication & safety guidance',
    openScanner: 'Open Medicine Scanner',
    myCabinetTitle: 'My Medicine Cabinet',
    myCabinetDesc: 'View your scanned medicines automatically grouped into disease shelves',
    openCabinet: 'Open My Cabinet',
    reportsRxTitle: 'Reports & Prescription AI',
    reportsRxDesc: 'Digitize doctor prescriptions (1-0-1 schedule) or audit blood lab reports',
    openReports: 'Open Reports & Rx',
    recentScans: 'Recent Medicine Scans',
    viewAllHistory: 'View All History',
    noScansYet: 'No medicine scans yet. Click Scanner to analyze your first medication packaging!',

    // Dashboard Therapeutic Cards
    cognitiveTitle: 'Cognitive Therapeutics & Memory Support',
    cognitiveSubtitle: 'Offline-first reminiscence memory exercises and automated audio reminders',
    offlineActive: 'Offline Active',
    reminiscenceMatchCard: 'Reminiscence Match',
    reminiscenceMatchDesc: 'Culturally contextual card matching with AI Dynamic Difficulty Adjustment (DDA).',
    launchGame: 'Launch Game',
    dailyVoiceRemindersCard: 'Daily Voice Reminders',
    dailyVoiceRemindersDesc: 'Interval hydration alerts and medication alarms with full-screen TTS modals.',
    viewSchedule: 'View Schedule',
    caregiverHubCard: 'Caregiver Clinical Hub',
    caregiverHubDesc: '7-day/30-day cognitive performance trajectories and >30% 3-day drop anomaly detector.',
    openAnalytics: 'Open Analytics',
    sanjeevaniVoiceAICard: 'Sanjeevani Voice AI',
    sanjeevaniVoiceAIDesc: 'Talk naturally in your local language. Spoken guidance for medicines & hydration.',
    talkWithVoiceAI: 'Talk with Voice AI',
    voiceTherapistCard: 'Dr. Ananya — Voice Therapist',
    voiceTherapistDesc: 'Real-time bidirectional Voice-to-Voice therapy session for calming anxiety & reminiscence.',
    enterTherapyRoom: 'Enter Voice Therapy Room',

    // Reminders & Modal
    drinkWater: '✓ I Drank Water',
    takeMedicine: '✓ I Took My Medicine',
    remind10Min: 'Remind Me in 10 Minutes',
    listenAgain: 'Listen to Voice Again',
    hydrationAlert: 'Time to Drink Water',
    medicationAlert: 'Time for Your Prescribed Medicine',

    // Scanner
    positionMedicine: 'Position Medicine Label Here',
    captureAnalyze: 'Capture & Analyze Medicine',
    uploadFile: 'Upload File',
    switchCam: 'Switch Cam',
    retakeScan: 'Retake / Scan Another',
    analyzing: 'Analyzing Medicine Packaging with AI Vision...',
    analyzingDesc: 'Reading optical text, active ingredients, dosage markings, and safety details',
    flashcards: 'Flashcards',
    singleColumn: 'Single Column',
    showAllCards: 'Show All Cards',
    carouselView: 'Flashcard Carousel',
    previousCard: 'Previous Card',
    nextCard: 'Next Card',
    cardXofY: 'Card {x} of {y}',
    primaryUse: 'Primary Uses & Indications',
    activeIngredients: 'Active Ingredients',
    dosageInstructions: 'Dosage Instructions',
    warnings: 'Critical Warnings & Precautions',
    sideEffects: 'Potential Side Effects',
    ncbiRecord: 'NCBI / NIH PubChem Record',
    aiPharmacist: 'AI Pharmacist Q&A Assistant',
    askPharmacist: 'Ask anything about this medicine...',
    askBtn: 'Ask',
    disclaimer: '* Disclaimer: PharmaVision AI is an assistive visual intelligence tool. Always confirm drug details with a qualified healthcare provider or pharmacist.',

    // Cabinet Page
    cabinetHeader: 'My Medicine Cabinet',
    cabinetSubtitle: 'All your scanned medicines automatically categorized into clinical disease shelves.',
    totalCabinetMeds: 'Total Cabinet Medicines',
    activeDiseaseCats: 'Active Disease Shelves',
    orgStatus: 'Categorization Status',
    allSorted: '100% Sorted',
    aiTaxonomy: 'AI Clinical Taxonomy Engine',
    searchPlaceholder: 'Search medicine name, salt, or disease…',
    allDiseases: 'All Diseases',
    medicinesCount: '{count} Medicines',
    addedOn: 'Added on {date}',
    viewDetails: 'View Details',
    emptyCabinet: 'Your Medicine Cabinet is Empty',
    emptyCabinetDesc: 'Scan medicine packaging or upload a prescription to automatically populate your disease shelves.',
    scanFirstMed: 'Scan Your First Medicine',

    // Reports & Rx Page
    reportsHeader: 'Reports & Prescription AI Intelligence',
    reportsSubtitle: 'Perform 360° dual consultation audits, extract 1-0-1 schedules from doctor prescriptions, or audit blood lab reports.',
    dualAuditTab: '⚡ Dual Audit (Lab + Rx)',
    rxDigitizerTab: 'Prescription Digitizer',
    labReportTab: 'Lab Report Analyzer',
    uploadBothDocs: 'Upload Both Medical Documents',
    dualAuditDesc: 'AI cross-references your lab biomarkers against prescribed drugs to identify contraindications and organ safety alerts.',
    doc1Lab: 'Document 1: Blood / Lab Report (PDF / Image)',
    clickUploadLab: 'Click to upload Lab Report',
    doc2Rx: 'Document 2: Doctor Prescription / Rx (PDF / Image)',
    clickUploadRx: 'Click to upload Doctor Prescription',
    runDualAuditBtn: 'Run 360° Dual Consultation Audit',
    uploadRxTitle: 'Upload Doctor Prescription (Rx)',
    rxUploadDesc: 'Handwritten scripts, clinic slips, and e-prescriptions supported (PDF, PNG, JPG)',
    digitizeRxBtn: 'Digitize Prescription & Extract Medicines',
    uploadLabTitle: 'Upload Blood / Lab Diagnostic Report',
    labUploadDesc: 'Complete blood count, lipid panel, metabolic profiles (up to 10MB)',
    analyzeLabBtn: 'Analyze Report & Cross-Check Cabinet',

    // Caregiver Hub
    caregiverHeader: 'Caregiver Clinical Intelligence Hub',
    caregiverSubtitle: 'Longitudinal cognitive trajectory tracking, routine adherence telemetry & clinical decline alerts.',
    trailing7Days: 'Trailing 7 Days',
    trailing30Days: 'Trailing 30 Days',
    manualSync: 'Sync Telemetry',
    syncingStatus: 'Syncing...',
    onlineMode: 'Cloud Connected',
    offlineStore: 'Offline Storage Active',
    avgAccuracy: 'Cognitive Accuracy',
    hesitationLatency: 'Hesitation Latency',
    hydrationCompliance: 'Hydration Adherence',
    medicationCompliance: 'Medication Adherence',
    trendlineTitle: 'Cognitive Accuracy & Hesitation Trendline',
    anomalyTitle: 'Clinical Decline Anomaly Detection',
    anomalyNormal: 'Cognitive status is stable with no acute deterioration detected.',
    anomalyWarning: 'Caution: Performance drop detected. Check for delirium, hydration, or medication side-effects.',

    // Timing & Schedule
    morning: 'Morning',
    afternoon: 'Afternoon',
    night: 'Night',
    duration: 'Duration',
    timing: 'Timing',
    saveToCabinet: 'Save ({count}) to Cabinet',
    selectedOf: 'Selected: {x} / {y}'
  },

  // ──────────────────────────── TELUGU (తెలుగు) ────────────────────────────
  te: {
    appName: 'Smriti Setu',
    tagline: 'డిమెన్షియా & జ్ఞాపకశక్తి సాంత్వన మరియు సంరక్షణ',
    home: 'హోమ్',
    scanner: 'మందుల స్కానర్',
    reportsRx: 'రిపోర్ట్‌లు & ప్రిస్క్రిప్షన్',
    cabinet: 'నా మెడిసిన్ క్యాబినెట్',
    cognitiveGames: 'జ్ఞాపకశక్తి ఆటలు',
    memoryReminders: 'రోజువారీ రిమైండర్లు',
    caregiverAnalytics: 'కేర్ గివర్ హబ్',
    history: 'చరిత్ర',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్ అవుట్',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    register: 'రిజిస్టర్',
    email: 'ఈమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    fullName: 'పూర్తి పేరు',
    alreadyAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    noAccount: 'ఖాతా లేదా? ఇప్పుడే నమోదు చేసుకోండి',
    selectLanguage: 'భాష ఎంచుకోండి',
    listenAudio: 'వినండి (ఆడియో)',
    speaking: 'చదువుతోంది...',
    voiceTherapist: 'వాయిస్ థెరపిస్ట్',
    voiceAI: 'వాయిస్ AI',

    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    dashboardSubtitle: 'మీ మందుల స్కానింగ్ మరియు ఆరోగ్య సమాచార సారాంశం.',
    totalScans: 'మొత్తం స్కాన్‌లు',
    allTimeScans: 'ఇప్పటివరకు విశ్లేషించిన మందులు',
    lastScanDate: 'చివరి స్కాన్ తేదీ',
    noRecentScans: 'ఇటీవలి స్కాన్‌లు లేవు',
    latestDrug: 'తాజా మందు వివరాలు',
    verifiedAI: 'AI విజన్ ద్వారా ధృవీకరించబడింది',
    scanNewMedicine: 'కొత్త మందును స్కాన్ చేయండి',
    scanNewDesc: 'మోతాదు, ఉపయోగం & భద్రతా వివరాల కోసం కెమెరాను మందు ప్యాకింగ్ వైపు చూపండి',
    openScanner: 'స్కానర్ తెరవండి',
    myCabinetTitle: 'నా మెడిసిన్ క్యాబినెట్',
    myCabinetDesc: 'స్కాన్ చేసిన మందులను వ్యాధి వారీ అరలలో క్రమపద్ధతిలో చూడండి',
    openCabinet: 'క్యాబినెట్ తెరవండి',
    reportsRxTitle: 'రిపోర్ట్‌లు & ప్రిస్క్రిప్షన్ AI',
    reportsRxDesc: 'డాక్టర్ ప్రిస్క్రిప్షన్‌లను డిజిటైజ్ చేయండి లేదా రక్త పరీక్ష రిపోర్టులను తనిఖీ చేయండి',
    openReports: 'రిపోర్ట్‌లను తెరవండి',
    recentScans: 'ఇటీవలి మందుల స్కాన్‌లు',
    viewAllHistory: 'మొత్తం చరిత్రను చూడండి',
    noScansYet: 'ఇంకా మందుల స్కాన్‌లు లేవు. ప్రారంభించడానికి స్కానర్‌ను నొక్కండి!',

    cognitiveTitle: 'జ్ఞాపకశక్తి చికిత్స & మద్దతు',
    cognitiveSubtitle: 'ఆఫ్‌లైన్ జ్ఞాపకశక్తి వ్యాయామాలు మరియు స్వయంచాలక వాయిస్ రిమైండర్లు',
    offlineActive: 'ఆఫ్‌లైన్ సక్రియం',
    reminiscenceMatchCard: 'జ్ఞాపకశక్తి మ్యాచింగ్ ఆట',
    reminiscenceMatchDesc: 'భారతీయ సాంస్కృతిక వస్తువులతో కూడిన 10 కష్టతరమైన స్థాయిల మెమరీ గేమ్.',
    launchGame: 'ఆటను ప్రారంభించండి',
    dailyVoiceRemindersCard: 'రోజువారీ వాయిస్ రిమైండర్లు',
    dailyVoiceRemindersDesc: 'మంచినీళ్లు మరియు సమయానికి మందులు వేసుకోవడానికి స్థానిక భాషా హెచ్చరికలు.',
    viewSchedule: 'షెడ్యూల్ చూడండి',
    caregiverHubCard: 'కేర్ గివర్ క్లినికల్ హబ్',
    caregiverHubDesc: 'జ్ఞాపకశక్తి స్థాయిల గ్రాఫ్ మరియు 30% కంటే ఎక్కువ తగ్గుదల ఉంటే హెచ్చరికలు.',
    openAnalytics: 'విశ్లేషణ తెరవండి',
    sanjeevaniVoiceAICard: 'సంజీవని వాయిస్ AI',
    sanjeevaniVoiceAIDesc: 'తెలుగులో మాట్లాడండి. మందులు మరియు ఆరోగ్యంపై తక్షణ సమాధానాలు పొందండి.',
    talkWithVoiceAI: 'వాయిస్‌తో మాట్లాడండి',
    voiceTherapistCard: 'డాక్టర్ అనన్య — వాయిస్ థెరపిస్ట్',
    voiceTherapistDesc: 'ఆందోళన తగ్గించడానికి, శ్వాస వ్యాయామాలు మరియు ఆప్యాయమైన సంభాషణ కోసం వాయిస్ గది.',
    enterTherapyRoom: 'థెరపీ గదిలోకి వెళ్ళండి',

    drinkWater: '✓ నేను నీళ్లు తాగాను',
    takeMedicine: '✓ నేను మందులు వేసుకున్నాను',
    remind10Min: '10 నిమిషాల తర్వాత గుర్తు చేయండి',
    listenAgain: 'వాయిస్ మళ్లీ వినండి',
    hydrationAlert: 'మంచినీళ్లు తాగే సమయం ఆసన్నమైంది',
    medicationAlert: 'డాక్టర్ సూచించిన మందులు వేసుకునే సమయం',

    positionMedicine: 'మందుల లేబుల్‌ను ఇక్కడ ఉంచండి',
    captureAnalyze: 'ఫోటో తీసి విశ్లేషించండి',
    uploadFile: 'ఫైల్ అప్‌లోడ్ చేయండి',
    switchCam: 'కెమెరా మార్చండి',
    retakeScan: 'మళ్లీ స్కాన్ చేయండి',
    analyzing: 'AI విజన్ ద్వారా మందుల ప్యాకింగ్ విశ్లేషణ జరుగుతోంది...',
    analyzingDesc: 'అక్షరాలు, పదార్థాలు, మోతాదు మరియు భద్రతా సమాచారాన్ని చదువుతోంది',
    flashcards: 'ఫ్లాష్‌కార్డులు',
    singleColumn: 'సింగిల్ కాలమ్',
    showAllCards: 'అన్ని కార్డులు చూపండి',
    carouselView: 'కార్డుల వరుస',
    previousCard: 'మునుపటి కార్డు',
    nextCard: 'తరువాతి కార్డు',
    cardXofY: 'కార్డు {x} / {y}',
    primaryUse: 'ప్రధాన ఉపయోగాలు & వ్యాధి సూచనలు',
    activeIngredients: 'క్రియాశీల పదార్థాలు (సాల్ట్స్)',
    dosageInstructions: 'మోతాదు & సమయ సూచనలు',
    warnings: 'ముఖ్యమైన హెచ్చరికలు & జాగ్రత్తలు',
    sideEffects: 'సంభావ్య దుష్ప్రభావాలు',
    ncbiRecord: 'NCBI / NIH పబ్‌కెమ్ రికార్డు',
    aiPharmacist: 'AI ఫార్మసిస్ట్ ప్రశ్నలు & జవాబులు',
    askPharmacist: 'ఈ మందు గురించి ఏదైనా అడగండి...',
    askBtn: 'అడగండి',
    disclaimer: '* గమనిక: ఫార్మావిజన్ AI ఒక సహాయక సాధనం మాత్రమే. మందుల వాడకానికి ముందు తప్పనిసరిగా వైద్యుడిని సంప్రదించండి.',

    cabinetHeader: 'నా మెడిసిన్ క్యాబినెట్',
    cabinetSubtitle: 'స్కాన్ చేసిన మందులన్నీ వ్యాధి విభాగాల వారీగా భద్రపరచబడ్డాయి.',
    totalCabinetMeds: 'మొత్తం క్యాబినెట్ మందులు',
    activeDiseaseCats: 'వ్యాధి అరల సంఖ్య',
    orgStatus: 'క్రమబద్ధీకరణ స్థితి',
    allSorted: '100% అమర్చబడింది',
    aiTaxonomy: 'AI క్లినికల్ వర్గీకరణ ఇంజిన్',
    searchPlaceholder: 'మందు పేరు, సాల్ట్ లేదా వ్యాధిని వెతకండి…',
    allDiseases: 'అన్ని విభాగాలు',
    medicinesCount: '{count} మందులు',
    addedOn: '{date} న చేర్చబడింది',
    viewDetails: 'వివరాలు చూడండి',
    emptyCabinet: 'మీ మెడిసిన్ క్యాబినెట్ ఖాళీగా ఉంది',
    emptyCabinetDesc: 'మందుల ప్యాకింగ్‌ను స్కాన్ చేయడం ద్వారా మీ అరలను నింపండి.',
    scanFirstMed: 'మొదటి మందును స్కాన్ చేయండి',

    reportsHeader: 'రిపోర్ట్‌లు & ప్రిస్క్రిప్షన్ AI ఇంటెలిజెన్స్',
    reportsSubtitle: 'రక్త పరీక్ష రిపోర్టులు మరియు ప్రిస్క్రిప్షన్‌లను తనిఖీ చేసి భద్రతను నిర్ధారించండి.',
    dualAuditTab: '⚡ ద్వంద్వ తనిఖీ (ల్యాబ్ + ప్రిస్క్రిప్షన్)',
    rxDigitizerTab: 'ప్రిస్క్రిప్షన్ రీడర్',
    labReportTab: 'ల్యాబ్ రిపోర్ట్ ఎనలైజర్',
    uploadBothDocs: 'రెండు వైద్య పత్రాలను అప్‌లోడ్ చేయండి',
    dualAuditDesc: 'మందుల వల్ల అవయవాలకు ఏదైనా హాని జరిగే అవకాశం ఉందా అని AI తనిఖీ చేస్తుంది.',
    doc1Lab: 'పత్రం 1: రక్త / ల్యాబ్ రిపోర్ట్',
    clickUploadLab: 'ల్యాబ్ రిపోర్ట్ ఎంచుకోండి',
    doc2Rx: 'పత్రం 2: డాక్టర్ ప్రిస్క్రిప్షన్',
    clickUploadRx: 'ప్రిస్క్రిప్షన్ ఎంచుకోండి',
    runDualAuditBtn: '360° ద్వంద్వ భద్రతా తనిఖీ ప్రారంభించండి',
    uploadRxTitle: 'డాక్టర్ ప్రిస్క్రిప్షన్ అప్‌లోడ్ చేయండి',
    rxUploadDesc: 'చేతిరాత స్లిప్‌లు మరియు ఇ-ప్రిస్క్రిప్షన్‌లు మద్దతు ఇవ్వబడతాయి',
    digitizeRxBtn: 'మందుల జాబితాను సేకరించండి',
    uploadLabTitle: 'రక్త పరీక్ష డయాగ్నస్టిక్ రిపోర్ట్',
    labUploadDesc: 'CBC, లిపిడ్ ప్రొఫైల్ మొదలైనవి',
    analyzeLabBtn: 'రిపోర్ట్‌ను విశ్లేషించండి',

    caregiverHeader: 'కేర్ గివర్ క్లినికల్ ఇంటెలిజెన్స్ హబ్',
    caregiverSubtitle: 'రోగి జ్ఞాపకశక్తి గ్రాఫ్, మందుల నియమ పాలన మరియు క్షీణత హెచ్చరికలు.',
    trailing7Days: 'గత 7 రోజులు',
    trailing30Days: 'గత 30 రోజులు',
    manualSync: 'సమాచారాన్ని సమకాలీకరించండి',
    syncingStatus: 'సమకాలీకరిస్తోంది...',
    onlineMode: 'క్లౌడ్ కనెక్ట్ అయింది',
    offlineStore: 'ఆఫ్‌లైన్ స్టోర్ సక్రియం',
    avgAccuracy: 'జ్ఞాపకశక్తి ఖచ్చితత్వం',
    hesitationLatency: 'ఆలోచన విరామ సమయం',
    hydrationCompliance: 'నీటి పాలన శాతం',
    medicationCompliance: 'మందుల నియమ శాతం',
    trendlineTitle: 'ఖచ్చితత్వం మరియు వేగం గ్రాఫ్',
    anomalyTitle: 'క్లినికల్ మార్పుల గుర్తింపు',
    anomalyNormal: 'జ్ఞాపకశక్తి స్థిరంగా ఉంది, ఎటువంటి ఆందోళనకర మార్పులు లేవు.',
    anomalyWarning: 'హెచ్చరిక: పనితీరు తగ్గింది. నీటి కొరత లేదా మందుల దుష్ప్రభావాలను తనిఖీ చేయండి.',

    morning: 'ఉదయం',
    afternoon: 'మధ్యాహ్నం',
    night: 'రాత్రి',
    duration: 'వ్యవధి',
    timing: 'సమయం',
    saveToCabinet: 'క్యాబినెట్‌లో భద్రపరచండి ({count})',
    selectedOf: 'ఎంచుకున్నవి: {x} / {y}'
  },

  // ──────────────────────────── HINDI (हिन्दी) ────────────────────────────
  hi: {
    appName: 'Smriti Setu',
    tagline: 'डिमेंशिया और स्मरण शक्ति स्वास्थ्य सेवा',
    home: 'होम',
    scanner: 'दवा स्कैनर',
    reportsRx: 'रिपोर्ट और पर्ची',
    cabinet: 'मेरी दवा अलमारी',
    cognitiveGames: 'स्मरण खेल',
    memoryReminders: 'दैनिक अनुस्मारक',
    caregiverAnalytics: 'देखभालकर्ता हब',
    history: 'इतिहास',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉगआउट',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    register: 'पंजीकरण करें',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    alreadyAccount: 'क्या पहले से खाता है?',
    noAccount: 'खाता नहीं है? अभी बनाएं',
    selectLanguage: 'भाषा चुनें',
    listenAudio: 'सुनें (ऑडियो)',
    speaking: 'बोला जा रहा है...',
    voiceTherapist: 'वॉइस थेरेपिस्ट',
    voiceAI: 'वॉइस एआई',

    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    dashboardSubtitle: 'आपकी दवा स्कैनिंग और स्वास्थ्य गतिविधि का संक्षिप्त विवरण।',
    totalScans: 'कुल स्कैन',
    allTimeScans: 'अब तक जांची गई दवाइयाँ',
    lastScanDate: 'अंतिम स्कैन तिथि',
    noRecentScans: 'कोई हालिया स्कैन नहीं',
    latestDrug: 'नवीनतम दवा',
    verifiedAI: 'एआई विज़न द्वारा सत्यापित',
    scanNewMedicine: 'नई दवा स्कैन करें',
    scanNewDesc: 'खुराक, उपयोग और सुरक्षा जानकारी के लिए दवा के पैकेट पर कैमरा दिखाएं',
    openScanner: 'दवा स्कैनर खोलें',
    myCabinetTitle: 'मेरी दवा अलमारी',
    myCabinetDesc: 'बीमारी के अनुसार क्रमबद्ध अलमारियों में अपनी दवाएं देखें',
    openCabinet: 'अलमारी खोलें',
    reportsRxTitle: 'रिपोर्ट और पर्ची एआई',
    reportsRxDesc: 'डॉक्टर की पर्ची डिजिटाइज़ करें या रक्त रिपोर्ट की जांच करें',
    openReports: 'रिपोर्ट खोलें',
    recentScans: 'हालिया दवा स्कैन',
    viewAllHistory: 'संपूर्ण इतिहास देखें',
    noScansYet: 'अभी कोई स्कैन नहीं है। पहली दवा जांचने के लिए स्कैनर दबाएं!',

    cognitiveTitle: 'स्मरण चिकित्सा और सहायता',
    cognitiveSubtitle: 'ऑफ़लाइन याददाश्त खेल और स्वचालित ध्वनि अनुस्मारक',
    offlineActive: 'ऑफ़लाइन सक्रिय',
    reminiscenceMatchCard: 'स्मरण मिलान खेल',
    reminiscenceMatchDesc: 'भारतीय संस्कृति पर आधारित 10 चुनौतीपूर्ण स्तरों का स्मरण खेल।',
    launchGame: 'खेल शुरू करें',
    dailyVoiceRemindersCard: 'दैनिक ध्वनि अनुस्मारक',
    dailyVoiceRemindersDesc: 'पानी पीने और समय पर दवा लेने के लिए स्थानीय भाषा में सतर्कता।',
    viewSchedule: 'शेड्यूल देखें',
    caregiverHubCard: 'देखभालकर्ता क्लीनिकल हब',
    caregiverHubDesc: 'याददाश्त का ग्राफ और गिरावट पर तत्काल क्लीनिकल अलर्ट।',
    openAnalytics: 'एनालिटिक्स खोलें',
    sanjeevaniVoiceAICard: 'संजीवनी वॉइस एआई',
    sanjeevaniVoiceAIDesc: 'हिंदी में बात करें और दवा व स्वास्थ्य पर तुरंत जवाब पाएं।',
    talkWithVoiceAI: 'वॉइस से बात करें',
    voiceTherapistCard: 'डॉ. अनन्या — वॉइस थेरेपिस्ट',
    voiceTherapistDesc: 'चिंता कम करने, गहरी सांस और अपनापन महसूस करने के लिए ध्वनि सत्र।',
    enterTherapyRoom: 'थेरेपी कक्ष में जाएं',

    drinkWater: '✓ मैंने पानी पी लिया',
    takeMedicine: '✓ मैंने दवा ले ली',
    remind10Min: '10 मिनट बाद याद दिलाएं',
    listenAgain: 'आवाज़ दोबारा सुनें',
    hydrationAlert: 'पानी पीने का समय हो गया है',
    medicationAlert: 'दवा लेने का सही समय',

    positionMedicine: 'दवा का लेबल यहाँ रखें',
    captureAnalyze: 'तस्वीर लें और जांचें',
    uploadFile: 'फ़ाइल अपलोड करें',
    switchCam: 'कैमरा बदलें',
    retakeScan: 'दोबारा स्कैन करें',
    analyzing: 'एआई विज़न द्वारा दवा के पैकेट की जांच हो रही है...',
    analyzingDesc: 'अक्षरों, साल्ट, खुराक और सुरक्षा विवरणों को पढ़ा जा रहा है',
    flashcards: 'फ़्लैशकार्ड',
    singleColumn: 'एकल कॉलम',
    showAllCards: 'सभी कार्ड दिखाएं',
    carouselView: 'कार्ड स्लाइडर',
    previousCard: 'पिछला कार्ड',
    nextCard: 'अगला कार्ड',
    cardXofY: 'कार्ड {x} / {y}',
    primaryUse: 'प्रमुख उपयोग और संकेत',
    activeIngredients: 'सक्रिय घटक (साल्ट)',
    dosageInstructions: 'खुराक और सेवन के नियम',
    warnings: 'महत्वपूर्ण सावधानियां और चेतावनियां',
    sideEffects: 'संभावित दुष्प्रभाव',
    ncbiRecord: 'NCBI / NIH पबकेम रिकॉर्ड',
    aiPharmacist: 'एआई फार्मासिस्ट प्रश्नोत्तर',
    askPharmacist: 'इस दवा के बारे में कुछ भी पूछें...',
    askBtn: 'पूछें',
    disclaimer: '* सूचना: यह केवल एक सहायक उपकरण है। दवा लेने से पहले डॉक्टर की सलाह अवश्य लें।',

    cabinetHeader: 'मेरी दवा अलमारी',
    cabinetSubtitle: 'आपकी स्कैन की गई सभी दवाएं बीमारी के अनुसार सुरक्षित हैं।',
    totalCabinetMeds: 'अलमारी में कुल दवाइयां',
    activeDiseaseCats: 'बीमारी श्रेणियों की संख्या',
    orgStatus: 'वर्गीकरण स्थिति',
    allSorted: '100% व्यवस्थित',
    aiTaxonomy: 'एआई क्लीनिकल वर्गीकरण',
    searchPlaceholder: 'दवा का नाम, साल्ट या बीमारी खोजें…',
    allDiseases: 'सभी श्रेणियां',
    medicinesCount: '{count} दवाइयां',
    addedOn: '{date} को जोड़ा गया',
    viewDetails: 'विवरण देखें',
    emptyCabinet: 'आपकी दवा अलमारी खाली है',
    emptyCabinetDesc: 'दवा का पैकेट स्कैन करें और अपनी अलमारी में जोड़ें।',
    scanFirstMed: 'पहली दवा स्कैन करें',

    reportsHeader: 'रिपोर्ट और पर्ची एआई',
    reportsSubtitle: 'रक्त परीक्षण और पर्ची का 360° ऑडिट कर सुरक्षा सुनिश्चित करें।',
    dualAuditTab: '⚡ दोहरा ऑडिट (लैब + पर्ची)',
    rxDigitizerTab: 'पर्ची डिजिटाइज़र',
    labReportTab: 'लैब रिपोर्ट विश्लेषक',
    uploadBothDocs: 'दोनों दस्तावेज अपलोड करें',
    dualAuditDesc: 'एआई जांचता है कि पर्चे की दवा आपकी लैब रिपोर्ट के अनुकूल है या नहीं।',
    doc1Lab: 'दस्तावेज 1: ब्लड / लैब रिपोर्ट',
    clickUploadLab: 'लैब रिपोर्ट चुनें',
    doc2Rx: 'दस्तावेज 2: डॉक्टर की पर्ची',
    clickUploadRx: 'पर्ची चुनें',
    runDualAuditBtn: '360° दोहरा सुरक्षा ऑडिट शुरू करें',
    uploadRxTitle: 'डॉक्टर की पर्ची अपलोड करें',
    rxUploadDesc: 'हस्तलिखित और ई-पर्चियां समर्थित हैं',
    digitizeRxBtn: 'दवाओं की सूची निकालें',
    uploadLabTitle: 'रक्त परीक्षण रिपोर्ट',
    labUploadDesc: 'सीबीसी, लिपिड प्रोफाइल आदि',
    analyzeLabBtn: 'रिपोर्ट जांचें',

    caregiverHeader: 'देखभालकर्ता क्लीनिकल हब',
    caregiverSubtitle: 'याददाश्त की प्रगति, दवा का समय और स्वास्थ्य सतर्कता।',
    trailing7Days: 'पिछले 7 दिन',
    trailing30Days: 'पिछले 30 दिन',
    manualSync: 'डेटा सिंक करें',
    syncingStatus: 'सिंक हो रहा है...',
    onlineMode: 'क्लाउड से जुड़ा हुआ',
    offlineStore: 'ऑफ़लाइन स्टोर सक्रिय',
    avgAccuracy: 'स्मरण सटीकता',
    hesitationLatency: 'सोचने में लगा समय',
    hydrationCompliance: 'जल सेवन प्रतिशत',
    medicationCompliance: 'दवा अनुपालन प्रतिशत',
    trendlineTitle: 'सटीकता और गति का रुझान',
    anomalyTitle: 'असामान्य गिरावट की पहचान',
    anomalyNormal: 'स्मरण शक्ति सामान्य और स्थिर है।',
    anomalyWarning: 'चेतावनी: प्रदर्शन में गिरावट दर्ज की गई है। डॉक्टर से परामर्श करें।',

    morning: 'सुबह',
    afternoon: 'दोपहर',
    night: 'रात',
    duration: 'अवधि',
    timing: 'समय',
    saveToCabinet: 'अलमारी में सहेजें ({count})',
    selectedOf: 'चयनित: {x} / {y}'
  },

  // ──────────────────────────── TAMIL (தமிழ்) ────────────────────────────
  ta: {
    appName: 'Smriti Setu',
    tagline: 'நினைவாற்றல் மற்றும் டிமென்ஷியா பராமரிப்பு நுண்ணறிவு',
    home: 'முகப்பு',
    scanner: 'மருந்து ஸ்கேனர்',
    reportsRx: 'அறிக்கைகள் & மருந்துச்சீட்டு',
    cabinet: 'என் மருந்து பெட்டி',
    cognitiveGames: 'நினைவாற்றல் விளையாட்டுகள்',
    memoryReminders: 'தினசரி நினைவூட்டல்',
    caregiverAnalytics: 'பராமரிப்பாளர் மையம்',
    history: 'வரலாறு',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    signIn: 'உள்நுழைக',
    signUp: 'பதிவு செய்க',
    register: 'பதிவு செய்க',
    email: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    fullName: 'முழு பெயர்',
    alreadyAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    noAccount: 'கணக்கு இல்லையா? பதிவு செய்க',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    listenAudio: 'கேட்க (ஆடியோ)',
    speaking: 'வாசிக்கிறது...',
    voiceTherapist: 'குரல் சிகிச்சையாளர்',
    voiceAI: 'குரல் AI',

    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    dashboardSubtitle: 'உங்கள் மருந்து ஸ்கேனிங் மற்றும் சுகாதார செயல்பாட்டின் சுருக்கம்.',
    totalScans: 'மொத்த ஸ்கேன்கள்',
    allTimeScans: 'ஆய்வு செய்யப்பட்ட மருந்துகள்',
    lastScanDate: 'கடைசி ஸ்கேன் தேதி',
    noRecentScans: 'சமீபத்திய ஸ்கேன்கள் இல்லை',
    latestDrug: 'சமீபத்திய மருந்து',
    verifiedAI: 'AI மூலம் சரிபார்க்கப்பட்டது',
    scanNewMedicine: 'புதிய மருந்தை ஸ்கேன் செய்க',
    scanNewDesc: 'அளவு மற்றும் பாதுகாப்பு வழிகாட்டுதலுக்கு கேமராவை மருந்து பாக்கெட்டில் வைக்கவும்',
    openScanner: 'ஸ்கேனரைத் திறக்க',
    myCabinetTitle: 'என் மருந்து பெட்டி',
    myCabinetDesc: 'நோய்களின் அடிப்படையில் அடுக்கப்பட்ட மருந்துகளைப் பார்க்கவும்',
    openCabinet: 'பெட்டியைத் திறக்க',
    reportsRxTitle: 'அறிக்கைகள் & மருந்துச்சீட்டு AI',
    reportsRxDesc: 'மருத்துவரின் மருந்துச்சீட்டை டிஜிட்டல் மயமாக்குங்கள் அல்லது இரத்த அறிக்கையை ஆராயுங்கள்',
    openReports: 'அறிக்கைகளைத் திறக்க',
    recentScans: 'சமீபத்திய மருந்து ஸ்கேன்கள்',
    viewAllHistory: 'முழு வரலாற்றைப் பார்க்க',
    noScansYet: 'ஸ்கேன்கள் எதுவும் இல்லை. தொடங்க ஸ்கேனரை அழுத்தவும்!',

    cognitiveTitle: 'நினைவாற்றல் சிகிச்சை & ஆதரவு',
    cognitiveSubtitle: 'ஆஃப்லைன் நினைவாற்றல் பயிற்சிகள் மற்றும் தானியங்கி குரல் நினைவூட்டல்கள்',
    offlineActive: 'ஆஃப்லைன் செயலில் உள்ளது',
    reminiscenceMatchCard: 'நினைவு பொருத்துதல் விளையாட்டு',
    reminiscenceMatchDesc: 'இந்திய கலாச்சாரப் பொருட்களுடன் கூடிய 10 நிலைகள் கொண்ட நினைவாற்றல் விளையாட்டு.',
    launchGame: 'விளையாட்டைத் தொடங்கவும்',
    dailyVoiceRemindersCard: 'தினசரி குரல் நினைவூட்டல்கள்',
    dailyVoiceRemindersDesc: 'தண்ணீர் குடிக்கவும் மருந்துகள் உட்கொள்ளவும் குரல் அறிவிப்புகள்.',
    viewSchedule: 'அட்டவணையைப் பார்க்க',
    caregiverHubCard: 'பராமரிப்பாளர் மையம்',
    caregiverHubDesc: 'நினைவாற்றல் வரைபடம் மற்றும் வீழ்ச்சி ஏற்பட்டால் எச்சரிக்கைகள்.',
    openAnalytics: 'பகுப்பாய்வைத் திறக்க',
    sanjeevaniVoiceAICard: 'சஞ்சீவனி குரல் AI',
    sanjeevaniVoiceAIDesc: 'தமிழில் பேசி மருந்து மற்றும் நல்வாழ்வு பற்றிய உடனடி பதில்களைப் பெறுங்கள்.',
    talkWithVoiceAI: 'குரல் மூலம் பேசுங்கள்',
    voiceTherapistCard: 'டாக்டர் அனன்யா — குரல் சிகிச்சையாளர்',
    voiceTherapistDesc: 'பதற்றத்தைக் குறைக்கவும் ஆறுதல் பெறவும் குரல் சிகிச்சை அமர்வு.',
    enterTherapyRoom: 'சிகிச்சை அறைக்குள் நுழையவும்',

    drinkWater: '✓ நான் தண்ணீர் குடித்தேன்',
    takeMedicine: '✓ நான் மருந்து உட்கொண்டேன்',
    remind10Min: '10 நிமிடங்களுக்குப் பிறகு நினைவூட்டு',
    listenAgain: 'குரலை மீண்டும் கேட்க',
    hydrationAlert: 'தண்ணீர் குடிக்கும் நேரம்',
    medicationAlert: 'மருந்து உட்கொள்ளும் நேரம்',

    positionMedicine: 'மருந்து லேபிளை இங்கே வைக்கவும்',
    captureAnalyze: 'புகைப்படம் எடுத்து பகுப்பாய்வு செய்க',
    uploadFile: 'கோப்பை பதிவேற்றவும்',
    switchCam: 'கேமராவை மாற்றவும்',
    retakeScan: 'மீண்டும் ஸ்கேன் செய்க',
    analyzing: 'மருந்து பகுப்பாய்வு செய்யப்படுகிறது...',
    analyzingDesc: 'பொருட்கள் மற்றும் பாதுகாப்பு விவரங்களைப் படிக்கிறது',
    flashcards: 'கார்டுகள்',
    singleColumn: 'ஒற்றை நிரல்',
    showAllCards: 'அனைத்து கார்டுகளையும் காட்டு',
    carouselView: 'கார்டு ஸ்லைடர்',
    previousCard: 'முந்தைய கார்டு',
    nextCard: 'அடுத்த கார்டு',
    cardXofY: 'கார்டு {x} / {y}',
    primaryUse: 'முக்கிய பயன்பாடுகள் மற்றும் அறிகுறிகள்',
    activeIngredients: 'செயலில் உள்ள பொருட்கள் (Salts)',
    dosageInstructions: 'மருந்து உட்கொள்ளும் வழிமுறைகள்',
    warnings: 'முக்கிய எச்சரிக்கைகள் மற்றும் முன்னெச்சரிக்கைகள்',
    sideEffects: 'பக்க விளைவுகள்',
    ncbiRecord: 'NCBI / NIH பதிவு',
    aiPharmacist: 'AI மருந்தாளர் கேள்வி பதில்',
    askPharmacist: 'இந்த மருந்தைப் பற்றி ஏதேனும் கேளுங்கள்...',
    askBtn: 'கேள்',
    disclaimer: '* மறுப்பு: இது ஒரு வழிகாட்டுதல் கருவி மட்டுமே. மருத்துவரை அணுகவும்.',

    cabinetHeader: 'என் மருந்து பெட்டி',
    cabinetSubtitle: 'உங்கள் மருந்துகள் அனைத்தும் நோய் வாரியாக அடுக்கப்பட்டுள்ளன.',
    totalCabinetMeds: 'மொத்த மருந்துகள்',
    activeDiseaseCats: 'பிரிவுகளின் எண்ணிக்கை',
    orgStatus: 'நிலை',
    allSorted: '100% வரிசைப்படுத்தப்பட்டது',
    aiTaxonomy: 'மருத்துவ வகைப்பாடு',
    searchPlaceholder: 'மருந்து அல்லது நோயைத் தேடவும்…',
    allDiseases: 'அனைத்து பிரிவுகளும்',
    medicinesCount: '{count} மருந்துகள்',
    addedOn: '{date} அன்று சேர்க்கப்பட்டது',
    viewDetails: 'விவரங்களைக் காண்க',
    emptyCabinet: 'மருந்து பெட்டி காலியாக உள்ளது',
    emptyCabinetDesc: 'மருந்துகளை ஸ்கேன் செய்து உங்கள் பெட்டியில் சேர்க்கவும்.',
    scanFirstMed: 'முதல் மருந்தை ஸ்கேன் செய்க',

    reportsHeader: 'அறிக்கைகள் & மருந்துச்சீட்டு AI',
    reportsSubtitle: 'இரத்தப் பரிசோதனை மற்றும் மருந்துச்சீட்டை ஆய்வு செய்து பாதுகாப்பை உறுதிப்படுத்தவும்.',
    dualAuditTab: '⚡ இரட்டை தணிக்கை (லேப் + மருந்துச்சீட்டு)',
    rxDigitizerTab: 'மருந்துச்சீட்டு ரீடர்',
    labReportTab: 'ஆய்வக அறிக்கை ஆய்வாளர்',
    uploadBothDocs: 'இரு ஆவணங்களையும் பதிவேற்றவும்',
    dualAuditDesc: 'மருந்துகள் உடலுக்கு பாதுகாப்பானவையா என AI சரிபார்க்கிறது.',
    doc1Lab: 'ஆவணம் 1: இரத்த அறிக்கை',
    clickUploadLab: 'அறிக்கையைத் தேர்ந்தெடுக்கவும்',
    doc2Rx: 'ஆவணம் 2: மருந்துச்சீட்டு',
    clickUploadRx: 'மருந்துச்சீட்டைத் தேர்ந்தெடுக்கவும்',
    runDualAuditBtn: '360° பாதுகாப்பு தணிக்கையைத் தொடங்கவும்',
    uploadRxTitle: 'மருந்துச்சீட்டைப் பதிவேற்றவும்',
    rxUploadDesc: 'கையெழுத்து மற்றும் மின்-மருந்துச்சீட்டுகள் ஏற்கப்படும்',
    digitizeRxBtn: 'மருந்துகளைப் பிரித்தெடுக்கவும்',
    uploadLabTitle: 'இரத்தப் பரிசோதனை அறிக்கை',
    labUploadDesc: 'CBC, கொலஸ்ட்ரால் போன்றவை',
    analyzeLabBtn: 'அறிக்கையை ஆய்வு செய்க',

    caregiverHeader: 'பராமரிப்பாளர் மையம்',
    caregiverSubtitle: 'நினைவாற்றல் முன்னேற்றம் மற்றும் ஆரோக்கிய வழிகாட்டுதல்.',
    trailing7Days: 'கடந்த 7 நாட்கள்',
    trailing30Days: 'கடந்த 30 நாட்கள்',
    manualSync: 'தரவை ஒத்திசைக்கவும்',
    syncingStatus: 'ஒத்திசைக்கப்படுகிறது...',
    onlineMode: 'இணைக்கப்பட்டது',
    offlineStore: 'ஆஃப்லைன் செயலில் உள்ளது',
    avgAccuracy: 'நினைவாற்றல் துல்லியம்',
    hesitationLatency: 'யோசிக்கும் நேரம்',
    hydrationCompliance: 'தண்ணீர் குடித்த சதவீதம்',
    medicationCompliance: 'மருந்து உட்கொண்ட சதவீதம்',
    trendlineTitle: 'துல்லியம் வரைபடம்',
    anomalyTitle: 'வீழ்ச்சி எச்சரிக்கை',
    anomalyNormal: 'நினைவாற்றல் நிலையாக உள்ளது.',
    anomalyWarning: 'எச்சரிக்கை: செயல்திறன் குறைந்துள்ளது. கவனிக்கவும்.',

    morning: 'காலை',
    afternoon: 'மதியம்',
    night: 'இரவு',
    duration: 'கால அளவு',
    timing: 'நேரம்',
    saveToCabinet: 'பெட்டியில் சேமிக்கவும் ({count})',
    selectedOf: 'தேர்ந்தெடுக்கப்பட்டது: {x} / {y}'
  },

  // ──────────────────────────── KANNADA (ಕನ್ನಡ) ────────────────────────────
  kn: {
    appName: 'Smriti Setu',
    tagline: 'ಸ್ಮರಣಶಕ್ತಿ ಮತ್ತು ಡಿಮೆನ್ಶಿಯಾ ಆರೈಕೆ ಬುದ್ಧಿವಂತಿಕೆ',
    home: 'ಮುಖಪುಟ',
    scanner: 'ಔಷಧಿ ಸ್ಕ್ಯಾನರ್',
    reportsRx: 'ವರದಿಗಳು & ಚೀಟಿ',
    cabinet: 'ನನ್ನ ಔಷಧಿ ಪೆಟ್ಟಿಗೆ',
    cognitiveGames: 'ಸ್ಮರಣ ಆಟಗಳು',
    memoryReminders: 'ದೈನಂದಿನ ನೆನಪೋಲೆ',
    caregiverAnalytics: 'ಆರೈಕೆದಾರರ ಹಬ್',
    history: 'ಇತಿಹಾಸ',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    signIn: 'ಸೈನ್ ಇನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    register: 'ನೋಂದಣಿ',
    email: 'ಇಮೇಲ್ ವಿಳಾಸ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    alreadyAccount: 'ಖಾತೆ ಇದೆಯೇ?',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ? ನೋಂದಾಯಿಸಿ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    listenAudio: 'ಆಲಿಸಿ (ಧ್ವನಿ)',
    speaking: 'ಓದಲಾಗುತ್ತಿದೆ...',
    voiceTherapist: 'ಧ್ವನಿ ಥೆರಪಿಸ್ಟ್',
    voiceAI: 'ಧ್ವನಿ AI',

    goodMorning: 'ಶುಭೋದಯ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    dashboardSubtitle: 'ನಿಮ್ಮ ಔಷಧಿ ಸ್ಕ್ಯಾನಿಂಗ್ ಮತ್ತು ಆರೋಗ್ಯ ಚಟುವಟಿಕೆಯ ಸಾರಾಂಶ.',
    totalScans: 'ಒಟ್ಟು ಸ್ಕ್ಯಾನ್‌ಗಳು',
    allTimeScans: 'ವಿಶ್ಲೇಷಿಸಲಾದ ಔಷಧಿಗಳು',
    lastScanDate: 'ಕೊನೆಯ ಸ್ಕ್ಯಾನ್ ದಿನಾಂಕ',
    noRecentScans: 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳಿಲ್ಲ',
    latestDrug: 'ಇತ್ತೀಚಿನ ಔಷಧಿ',
    verifiedAI: 'AI ದೃಢೀಕರಿಸಿದೆ',
    scanNewMedicine: 'ಹೊಸ ಔಷಧಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    scanNewDesc: 'ಪ್ರಮಾಣ ಮತ್ತು ಸುರಕ್ಷತಾ ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ಕ್ಯಾಮರಾವನ್ನು ಪ್ಯಾಕೆಟ್‌ಗೆ ತೋರಿಸಿ',
    openScanner: 'ಸ್ಕ್ಯಾನರ್ ತೆರೆಯಿರಿ',
    myCabinetTitle: 'ನನ್ನ ಔಷಧಿ ಪೆಟ್ಟಿಗೆ',
    myCabinetDesc: 'ರೋಗವಾರು ವಿಂಗಡಿಸಲಾದ ನಿಮ್ಮ ಔಷಧಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    openCabinet: 'ಪೆಟ್ಟಿಗೆ ತೆರೆಯಿರಿ',
    reportsRxTitle: 'ವರದಿಗಳು & ಚೀಟಿ AI',
    reportsRxDesc: 'ವೈದ್ಯರ ಚೀಟಿಯನ್ನು ಡಿಜಿಟೈಸ್ ಮಾಡಿ ಅಥವಾ ರಕ್ತ ವರದಿಯನ್ನು ಪರೀಕ್ಷಿಸಿ',
    openReports: 'ವರದಿಗಳನ್ನು ತೆರೆಯಿರಿ',
    recentScans: 'ಇತ್ತೀಚಿನ ಔಷಧಿ ಸ್ಕ್ಯಾನ್‌ಗಳು',
    viewAllHistory: 'ಪೂರ್ಣ ಇತಿಹಾಸ ನೋಡಿ',
    noScansYet: 'ಯಾವುದೇ ಸ್ಕ್ಯಾನ್‌ಗಳಿಲ್ಲ. ಪ್ರಾರಂಭಿಸಲು ಸ್ಕ್ಯಾನರ್ ಒತ್ತಿ!',

    cognitiveTitle: 'ಸ್ಮರಣ ಚಿಕಿತ್ಸೆ & ಬೆಂಬಲ',
    cognitiveSubtitle: 'ಆಫ್‌ಲೈನ್ ಸ್ಮರಣ ಆಟಗಳು ಮತ್ತು ಸ್ವಯಂಚಾಲಿತ ಧ್ವನಿ ನೆನಪೋಲೆಗಳು',
    offlineActive: 'ಆಫ್‌ಲೈನ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    reminiscenceMatchCard: 'ಸ್ಮರಣ ಹೊಂದಾಣಿಕೆ ಆಟ',
    reminiscenceMatchDesc: 'ಭಾರತೀಯ ಸಾಂಸ್ಕೃತಿಕ ವಸ್ತುಗಳೊಂದಿಗೆ 10 ಹಂತಗಳ ಸ್ಮರಣ ಆಟ.',
    launchGame: 'ಆಟ ಪ್ರಾರಂಭಿಸಿ',
    dailyVoiceRemindersCard: 'ದೈನಂದಿನ ಧ್ವನಿ ನೆನಪೋಲೆಗಳು',
    dailyVoiceRemindersDesc: 'ನೀರು ಕುಡಿಯಲು ಮತ್ತು ಮಾತ್ರೆಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ಧ್ವನಿ ಸೂಚನೆಗಳು.',
    viewSchedule: 'ವೇಳಾಪಟ್ಟಿ ನೋಡಿ',
    caregiverHubCard: 'ಆರೈಕೆದಾರರ ಹಬ್',
    caregiverHubDesc: 'ಸ್ಮರಣಶಕ್ತಿಯ ಪ್ರಗತಿ ಮತ್ತು ಇಳಿಕೆಯಾದರೆ ಎಚ್ಚರಿಕೆಗಳು.',
    openAnalytics: 'ವಿಶ್ಲೇಷಣೆ ತೆರೆಯಿರಿ',
    sanjeevaniVoiceAICard: 'ಸಂಜೀವನಿ ಧ್ವನಿ AI',
    sanjeevaniVoiceAIDesc: 'ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ ಔಷಧಿ ಮತ್ತು ಆರೋಗ್ಯದ ಬಗ್ಗೆ ತಕ್ಷಣ ಮಾಹಿತಿ ಪಡೆಯಿರಿ.',
    talkWithVoiceAI: 'ಧ್ವನಿಯೊಂದಿಗೆ ಮಾತನಾಡಿ',
    voiceTherapistCard: 'ಡಾ. ಅನನ್ಯಾ — ಧ್ವನಿ ಥೆರಪಿಸ್ಟ್',
    voiceTherapistDesc: 'ಆತಂಕ ನಿವಾರಣೆ ಮತ್ತು ಆಪ್ತ ಸಮಾಲೋಚನೆಗಾಗಿ ಧ್ವನಿ ಕೊಠಡಿ.',
    enterTherapyRoom: 'ಥೆರಪಿ ಕೊಠಡಿಗೆ ಹೋಗಿ',

    drinkWater: '✓ ನಾನು ನೀರು ಕುಡಿದೆ',
    takeMedicine: '✓ ನಾನು ಮಾತ್ರೆ ತಗೊಂಡೆ',
    remind10Min: '10 ನಿಮಿಷಗಳ ನಂತರ ನೆನಪಿಸಿ',
    listenAgain: 'ಧ್ವನಿ ಪುನಃ ಆಲಿಸಿ',
    hydrationAlert: 'ನೀರು ಕುಡಿಯುವ ಸಮಯವಾಗಿದೆ',
    medicationAlert: 'ಮಾತ್ರೆಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುವ ಸಮಯ',

    positionMedicine: 'ಔಷಧಿಯ ಲೇಬಲ್ ಇಲ್ಲಿ ಇರಿಸಿ',
    captureAnalyze: 'ಫೋಟೋ ತೆಗೆದು ವಿಶ್ಲೇಷಿಸಿ',
    uploadFile: 'ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    switchCam: 'ಕ್ಯಾಮರಾ ಬದಲಾಯಿಸಿ',
    retakeScan: 'ಪುನಃ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    analyzing: 'ಔಷಧಿಯ ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ...',
    analyzingDesc: 'ಪದಾರ್ಥಗಳು ಮತ್ತು ಸುರಕ್ಷತಾ ವಿವರಗಳನ್ನು ಓದಲಾಗುತ್ತಿದೆ',
    flashcards: 'ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್‌ಗಳು',
    singleColumn: 'ಏಕ ಕಾಲಮ್',
    showAllCards: 'ಎಲ್ಲಾ ಕಾರ್ಡ್ ತೋರಿಸಿ',
    carouselView: 'ಕಾರ್ಡ್ ಸ್ಲೈಡರ್',
    previousCard: 'ಹಿಂದಿನ ಕಾರ್ಡ್',
    nextCard: 'ಮುಂದಿನ ಕಾರ್ಡ್',
    cardXofY: 'ಕಾರ್ಡ್ {x} / {y}',
    primaryUse: 'ಪ್ರಮುಖ ಉಪಯೋಗಗಳು ಮತ್ತು ಸೂಚನೆಗಳು',
    activeIngredients: 'ಸಕ್ರಿಯ ಪದಾರ್ಥಗಳು (Salts)',
    dosageInstructions: 'ಔಷಧಿ ಸೇವನೆಯ ನಿಯಮಗಳು',
    warnings: 'ಪ್ರಮುಖ ಎಚ್ಚರಿಕೆಗಳು',
    sideEffects: 'ಅಡ್ಡ ಪರಿಣಾಮಗಳು',
    ncbiRecord: 'NCBI ದಾಖಲೆ',
    aiPharmacist: 'AI ಫಾರ್ಮಸಿಸ್ಟ್ ಪ್ರಶ್ನೋತ್ತರ',
    askPharmacist: 'ಈ ಔಷಧಿಯ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ...',
    askBtn: 'ಕೇಳಿ',
    disclaimer: '* ಸೂಚನೆ: ಇದು ಕೇವಲ ಸಹಾಯಕ ಸಾಧನ. ವೈದ್ಯರ ಸಲಹೆ ಪಡೆಯಿರಿ.',

    cabinetHeader: 'ನನ್ನ ಔಷಧಿ ಪೆಟ್ಟಿಗೆ',
    cabinetSubtitle: 'ನಿಮ್ಮ ಎಲ್ಲಾ ಔಷಧಿಗಳನ್ನು ರೋಗವಾರು ಸಂಗ್ರಹಿಸಲಾಗಿದೆ.',
    totalCabinetMeds: 'ಒಟ್ಟು ಔಷಧಿಗಳು',
    activeDiseaseCats: 'ವರ್ಗಗಳ ಸಂಖ್ಯೆ',
    orgStatus: 'ಸ್ಥಿತಿ',
    allSorted: '100% ಜೋಡಿಸಲಾಗಿದೆ',
    aiTaxonomy: 'ಕ್ಲಿನಿಕಲ್ ವರ್ಗೀಕರಣ',
    searchPlaceholder: 'ಔಷಧಿ ಅಥವಾ ಕಾಯಿಲೆ ಹುಡುಕಿ…',
    allDiseases: 'ಎಲ್ಲಾ ವಿಭಾಗಗಳು',
    medicinesCount: '{count} ಔಷಧಿಗಳು',
    addedOn: '{date} ರಂದು ಸೇರಿಸಲಾಗಿದೆ',
    viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    emptyCabinet: 'ಪೆಟ್ಟಿಗೆ ಖಾಲಿಯಾಗಿದೆ',
    emptyCabinetDesc: 'ಪ್ಯಾಕೆಟ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ನಿಮ್ಮ ಪೆಟ್ಟಿಗೆಗೆ ಸೇರಿಸಿ.',
    scanFirstMed: 'ಮೊದಲ ಔಷಧಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',

    reportsHeader: 'ವರದಿಗಳು & ಚೀಟಿ AI',
    reportsSubtitle: 'ರಕ್ತ ವರದಿ ಮತ್ತು ಚೀಟಿಯನ್ನು ಪರಿಶೀಲಿಸಿ ಸುರಕ್ಷತೆ ಖಚಿತಪಡಿಸಿ.',
    dualAuditTab: '⚡ ದ್ವಿಮುಖ ತಪಾಸಣೆ (ಲ್ಯಾಬ್ + ಚೀಟಿ)',
    rxDigitizerTab: 'ಚೀಟಿ ರೀಡರ್',
    labReportTab: 'ಲ್ಯಾಬ್ ವರದಿ ವಿಶ್ಲೇಷಕ',
    uploadBothDocs: 'ಎರಡೂ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    dualAuditDesc: 'ಔಷಧಿಗಳು ಸುರಕ್ಷಿತವೇ ಎಂದು AI ಪರಿಶೀಲಿಸುತ್ತದೆ.',
    doc1Lab: 'ದಾಖಲೆ 1: ರಕ್ತ ವರದಿ',
    clickUploadLab: 'ವರದಿ ಆಯ್ಕೆಮಾಡಿ',
    doc2Rx: 'ದಾಖಲೆ 2: ವೈದ್ಯರ ಚೀಟಿ',
    clickUploadRx: 'ಚೀಟಿ ಆಯ್ಕೆಮಾಡಿ',
    runDualAuditBtn: '360° ಸುರಕ್ಷತಾ ತಪಾಸಣೆ ಪ್ರಾರಂಭಿಸಿ',
    uploadRxTitle: 'ವೈದ್ಯರ ಚೀಟಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    rxUploadDesc: 'ಕೈಬರಹ ಮತ್ತು ಇ-ಚೀಟಿಗಳು ಬೆಂಬಲಿತವಾಗಿವೆ',
    digitizeRxBtn: 'ಔಷಧಿಗಳ ಪಟ್ಟಿ ಹೊರತೆಗೆಯಿರಿ',
    uploadLabTitle: 'ರಕ್ತ ಪರೀಕ್ಷಾ ವರದಿ',
    labUploadDesc: 'ಸಿಬಿಸಿ, ಲಿಪಿಡ್ ಪ್ರೊಫೈಲ್ ಇತ್ಯಾದಿ',
    analyzeLabBtn: 'ವರದಿ ವಿಶ್ಲೇಷಿಸಿ',

    caregiverHeader: 'ಆರೈಕೆದಾರರ ಹಬ್',
    caregiverSubtitle: 'ಸ್ಮರಣಶಕ್ತಿಯ ಪ್ರಗತಿ ಮತ್ತು ಆರೈಕೆ ಮಾಹಿತಿ.',
    trailing7Days: 'ಕಳೆದ 7 ದಿನಗಳು',
    trailing30Days: 'ಕಳೆದ 30 ದಿನಗಳು',
    manualSync: 'ಡೇಟಾ ಸಿಂಕ್ ಮಾಡಿ',
    syncingStatus: 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
    onlineMode: 'ಸಂಪರ್ಕಗೊಂಡಿದೆ',
    offlineStore: 'ಆಫ್‌ಲೈನ್ ಸಂಗ್ರಹ ಸಕ್ರಿಯ',
    avgAccuracy: 'ಸ್ಮರಣ ನಿಖರತೆ',
    hesitationLatency: 'ಯೋಚಿಸುವ ಸಮಯ',
    hydrationCompliance: 'ನೀರು ಸೇವನೆಯ ಪ್ರಮಾಣ',
    medicationCompliance: 'ಔಷಧಿ ಸೇವನೆಯ ನಿಯಮ',
    trendlineTitle: 'ನಿಖರತೆ ನಕ್ಷೆ',
    anomalyTitle: 'ಕುಸಿತದ ಎಚ್ಚರಿಕೆ',
    anomalyNormal: 'ಸ್ಮರಣಶಕ್ತಿ ಸ್ಥಿರವಾಗಿದೆ.',
    anomalyWarning: 'ಎಚ್ಚರಿಕೆ: ಕಾರ್ಯಕ್ಷಮತೆ ಕಡಿಮೆಯಾಗಿದೆ. ಗಮನಿಸಿ.',

    morning: 'ಮುಂಜಾನೆ',
    afternoon: 'ಮಧ್ಯಾಹ್ನ',
    night: 'ರಾತ್ರಿ',
    duration: 'ಅವಧಿ',
    timing: 'ಸಮಯ',
    saveToCabinet: 'ಪೆಟ್ಟಿಗೆಗೆ ಉಳಿಸಿ ({count})',
    selectedOf: 'ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ: {x} / {y}'
  },

  // ──────────────────────────── BENGALI (বাংলা) ────────────────────────────
  bn: {
    appName: 'Smriti Setu',
    tagline: 'ডিমেনশিয়া ও স্মৃতিচর্চা যত্ন ব্যবস্থা',
    home: 'হোম',
    scanner: 'ওষুধ স্ক্যানার',
    reportsRx: 'রিপোর্ট ও প্রেসক্রিপশন',
    cabinet: 'আমার ওষুধের বাক্স',
    cognitiveGames: 'স্মৃতিচর্চা খেলা',
    memoryReminders: 'দৈনিক অনুস্মারক',
    caregiverAnalytics: 'কেয়ারগিভার হাব',
    history: 'ইতিহাস',
    profile: 'প্রোফাইল',
    logout: 'লগআউট',
    signIn: 'সাইন ইন',
    signUp: 'সাইন আপ',
    register: 'নিবন্ধন',
    email: 'ইমেল ঠিকানা',
    password: 'পাসওয়ার্ড',
    fullName: 'সম্পূর্ণ নাম',
    alreadyAccount: 'অ্যাকাউন্ট আছে?',
    noAccount: 'অ্যাকাউন্ট নেই? নিবন্ধন করুন',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    listenAudio: 'শুনুন (অডিও)',
    speaking: 'পড়া হচ্ছে...',
    voiceTherapist: 'ভয়েস থেরাপিস্ট',
    voiceAI: 'ভয়েস এআই',

    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ দুপুর',
    goodEvening: 'শুভ সন্ধ্যা',
    dashboardSubtitle: 'আপনার ওষুধ স্ক্যানিং এবং স্বাস্থ্য কার্যকলাপের সারসংক্ষেপ।',
    totalScans: 'মোট স্ক্যান',
    allTimeScans: 'বিশ্লেষিত ওষুধ',
    lastScanDate: 'সর্বশেষ স্ক্যানের তারিখ',
    noRecentScans: 'কোনো সাম্প্রতিক স্ক্যান নেই',
    latestDrug: 'সর্বশেষ ওষুধ',
    verifiedAI: 'এআই যাচাইকৃত',
    scanNewMedicine: 'নতুন ওষুধ স্ক্যান করুন',
    scanNewDesc: 'ডোজ ও সুরক্ষার জন্য ওষুধের প্যাকেটে ক্যামেরা ধরুন',
    openScanner: 'স্ক্যানার খুলুন',
    myCabinetTitle: 'আমার ওষুধের বাক্স',
    myCabinetDesc: 'রোগ অনুযায়ী সাজানো আপনার ওষুধগুলি দেখুন',
    openCabinet: 'বাক্স খুলুন',
    reportsRxTitle: 'রিপোর্ট ও প্রেসক্রিপশন এআই',
    reportsRxDesc: 'প্রেসক্রিপশন ডিজিটাইজ করুন অথবা ল্যাব রিপোর্ট পরীক্ষা করুন',
    openReports: 'রিপোর্ট খুলুন',
    recentScans: 'সাম্প্রতিক ওষুধ স্ক্যান',
    viewAllHistory: 'সম্পূর্ণ ইতিহাস দেখুন',
    noScansYet: 'এখনও কোনো স্ক্যান নেই। শুরু করতে স্ক্যানার চাপুন!',

    cognitiveTitle: 'স্মৃতিচর্চা ও সহায়তা',
    cognitiveSubtitle: 'অফলাইন স্মৃতিশক্তি খেলা এবং স্বয়ংক্রিয় ভয়েস অনুস্মারক',
    offlineActive: 'অফলাইন সক্রিয়',
    reminiscenceMatchCard: 'স্মৃতি মিলানোর খেলা',
    reminiscenceMatchDesc: 'ভারতীয় ঐতিহ্যবাহী বস্তুর সাথে ১০টি চ্যালেঞ্জিং লেভেলের স্মৃতি খেলা।',
    launchGame: 'খেলা শুরু করুন',
    dailyVoiceRemindersCard: 'দৈনিক ভয়েস অনুস্মারক',
    dailyVoiceRemindersDesc: 'জল পান এবং নিয়ম মেনে ওষুধ খাওয়ার জন্য আঞ্চলিক ভাষায় সতর্কতা।',
    viewSchedule: 'সময়সূচী দেখুন',
    caregiverHubCard: 'কেয়ারগিভার হাব',
    caregiverHubDesc: 'স্মৃতিশক্তির গ্রাফ এবং অবনতি হলে তাৎক্ষণিক ক্লিনিকাল অ্যালার্ট।',
    openAnalytics: 'অ্যানালিটিক্স খুলুন',
    sanjeevaniVoiceAICard: 'সঞ্জীবনী ভয়েস এআই',
    sanjeevaniVoiceAIDesc: 'বাংলায় কথা বলুন এবং ওষুধ ও স্বাস্থ্য নিয়ে সাথে সাথে উত্তর পান।',
    talkWithVoiceAI: 'ভয়েসে কথা বলুন',
    voiceTherapistCard: 'ডাঃ অনন্যা — ভয়েস থেরাপিস্ট',
    voiceTherapistDesc: 'উদ্বেগ কমাতে, শান্ত হতে এবং আপনজনের মতো কথা বলার জন্য থেরাপি কক্ষ।',
    enterTherapyRoom: 'থেরাপি কক্ষে প্রবেশ করুন',

    drinkWater: '✓ আমি জল খেয়েছি',
    takeMedicine: '✓ আমি ওষুধ খেয়েছি',
    remind10Min: '১০ মিনিট পরে মনে করান',
    listenAgain: 'আওয়াজ পুনরায় শুনুন',
    hydrationAlert: 'জল খাওয়ার সময় হয়েছে',
    medicationAlert: 'ওষুধ খাওয়ার সময় হয়েছে',

    positionMedicine: 'ওষুধের লেবেল এখানে রাখুন',
    captureAnalyze: 'ছবি তুলুন ও বিশ্লেষণ করুন',
    uploadFile: 'ফাইল আপলোড করুন',
    switchCam: 'ক্যামেরা বদলান',
    retakeScan: 'পুনরায় স্ক্যান করুন',
    analyzing: 'ওষুধ বিশ্লেষণ করা হচ্ছে...',
    analyzingDesc: 'উপাদান ও সুরক্ষার নিয়ম পড়া হচ্ছে',
    flashcards: 'ফ্ল্যাশকার্ড',
    singleColumn: 'একক কলাম',
    showAllCards: 'সব কার্ড দেখান',
    carouselView: 'কার্ড স্লাইডার',
    previousCard: 'পূর্ববর্তী কার্ড',
    nextCard: 'পরবর্তী কার্ড',
    cardXofY: 'কার্ড {x} / {y}',
    primaryUse: 'প্রধান ব্যবহার ও নির্দেশিকা',
    activeIngredients: 'সক্রিয় উপাদান (Salts)',
    dosageInstructions: 'ডোজ ও সেবনের নিয়মাবলী',
    warnings: 'জরুরী সতর্কতা',
    sideEffects: 'পার্শ্বপ্রতিক্রিয়া',
    ncbiRecord: 'NCBI রেকর্ড',
    aiPharmacist: 'এআই ফার্মাসিস্ট প্রশ্নোত্তর',
    askPharmacist: 'এই ওষুধ সম্পর্কে কিছু জিজ্ঞাসা করুন...',
    askBtn: 'জিজ্ঞাসা করুন',
    disclaimer: '* তথ্য: এটি শুধুমাত্র সহায়ক প্রযুক্তি। চিকিৎসকের পরামর্শ নিন।',

    cabinetHeader: 'আমার ওষুধের বাক্স',
    cabinetSubtitle: 'আপনার ওষুধগুলি রোগ অনুযায়ী সুরক্ষিত রাখা হয়েছে।',
    totalCabinetMeds: 'মোট ওষুধ',
    activeDiseaseCats: 'বিভাগের সংখ্যা',
    orgStatus: 'অবস্থা',
    allSorted: '১০০% সাজানো',
    aiTaxonomy: 'ক্লিনিকাল শ্রেণীবিন্যাস',
    searchPlaceholder: 'ওষুধ বা রোগ খুঁজুন…',
    allDiseases: 'সকল বিভাগ',
    medicinesCount: '{count}টি ওষুধ',
    addedOn: '{date} তারিখে যুক্ত',
    viewDetails: 'বিস্তারিত দেখুন',
    emptyCabinet: 'ওষুধের বাক্স খালি',
    emptyCabinetDesc: 'প্যাকেট স্ক্যান করে আপনার বাক্সে যুক্ত করুন।',
    scanFirstMed: 'প্রথম ওষুধ স্ক্যান করুন',

    reportsHeader: 'রিপোর্ট ও প্রেসক্রিপশন এআই',
    reportsSubtitle: 'রক্তের রিপোর্ট ও প্রেসক্রিপশন পরীক্ষা করে সুরক্ষা নিশ্চিত করুন।',
    dualAuditTab: '⚡ দ্বিমুখী নিরীক্ষা (ল্যাব + প্রেসক্রিপশন)',
    rxDigitizerTab: 'প্রেসক্রিপশন রিডার',
    labReportTab: 'ল্যাব রিপোর্ট অ্যানালাইজার',
    uploadBothDocs: 'উভয় নথি আপলোড করুন',
    dualAuditDesc: 'ওষুধ শরীরের জন্য নিরাপদ কিনা তা এআই পরীক্ষা করে।',
    doc1Lab: 'নথি ১: রক্তের রিপোর্ট',
    clickUploadLab: 'রিপোর্ট নির্বাচন করুন',
    doc2Rx: 'নথি ২: প্রেসক্রিপশন',
    clickUploadRx: 'প্রেসক্রিপশন নির্বাচন করুন',
    runDualAuditBtn: '৩৬০° দ্বিমুখী নিরীক্ষা শুরু করুন',
    uploadRxTitle: 'প্রেসক্রিপশন আপলোড করুন',
    rxUploadDesc: 'হাতে লেখা এবং ডিজিটাল প্রেসক্রিপশন সমর্থিত',
    digitizeRxBtn: 'ওষুধের তালিকা বের করুন',
    uploadLabTitle: 'রক্ত পরীক্ষার রিপোর্ট',
    labUploadDesc: 'সিবিসি, লিপিড প্রোফাইল ইত্যাদি',
    analyzeLabBtn: 'রিপোর্ট বিশ্লেষণ করুন',

    caregiverHeader: 'কেয়ারগিভার হাব',
    caregiverSubtitle: 'স্মৃতিশক্তির অগ্রগতি ও স্বাস্থ্য পর্যবেক্ষণ।',
    trailing7Days: 'গত ৭ দিন',
    trailing30Days: 'গত ৩০ দিন',
    manualSync: 'ডেটা সিঙ্ক করুন',
    syncingStatus: 'সিঙ্ক হচ্ছে...',
    onlineMode: 'সংযুক্ত আছে',
    offlineStore: 'অফলাইন স্টোর সক্রিয়',
    avgAccuracy: 'স্মৃতিশক্তির নির্ভুলতা',
    hesitationLatency: 'ভাবার সময়কাল',
    hydrationCompliance: 'জল পানের শতকরা হার',
    medicationCompliance: 'ওষুধ খাওয়ার শতকরা হার',
    trendlineTitle: 'নির্ভুলতার গ্রাফ',
    anomalyTitle: 'অবনতি সতর্কতা',
    anomalyNormal: 'স্মৃতিশক্তি স্থিতিশীল রয়েছে।',
    anomalyWarning: 'সতর্কতা: পারফরম্যান্সে অবনতি লক্ষ্য করা গেছে।',

    morning: 'সকাল',
    afternoon: 'দুপুর',
    night: 'রাত',
    duration: 'মেয়াদ',
    timing: 'সময়সূচী',
    saveToCabinet: 'বাক্সে সংরক্ষণ করুন ({count})',
    selectedOf: 'নির্বাচিত: {x} / {y}'
  },

  // ──────────────────────────── ASSAMESE (অসমীয়া) ────────────────────────────
  as: {
    appName: 'Smriti Setu',
    tagline: 'স্মৃতিশক্তি আৰু ডিমেনচিয়া সেৱা বুদ্ধিমত্তা',
    home: 'মুখ্যপৃষ্ঠা',
    scanner: 'ঔষধ স্কেনাৰ',
    reportsRx: 'প্ৰতিবেদন আৰু প্ৰেছক্ৰিপশ্বন',
    cabinet: 'মোৰ ঔষধৰ বাকচ',
    cognitiveGames: 'স্মৃতিশক্তি খেল',
    memoryReminders: 'দৈনিক সোঁৱৰণি',
    caregiverAnalytics: 'যত্নশীল ব্যক্তিৰ হাব',
    history: 'ইতিহাস',
    profile: 'প্ৰফাইল',
    logout: 'লগআউট',
    signIn: 'ছাইন ইন',
    signUp: 'ছাইন আপ',
    register: 'পঞ্জীয়ন',
    email: 'ইমেইল ঠিকনা',
    password: 'পাছৱৰ্ড',
    fullName: 'সম্পূৰ্ণ নাম',
    alreadyAccount: 'একাউণ্ট আছে নেকি?',
    noAccount: 'একাউণ্ট নাই? পঞ্জীয়ন কৰক',
    selectLanguage: 'ভাষা বাছক',
    listenAudio: 'শুনক (অডিঅ\')',
    speaking: 'পঢ়া হৈছে...',
    voiceTherapist: 'ভইচ থেৰাপিষ্ট',
    voiceAI: 'ভইচ এআই',

    goodMorning: 'শুভ ৰাতিপুৱা',
    goodAfternoon: 'শুভ দুপৰীয়া',
    goodEvening: 'শুভ গধূলি',
    dashboardSubtitle: 'আপোনাৰ ঔষধ স্কেনিং আৰু স্বাস্থ্য কাৰ্য্যকলাপৰ সাৰাংশ।',
    totalScans: 'মুঠ স্কেন',
    allTimeScans: 'বিশ্লেষিত ঔষধ',
    lastScanDate: 'অন্তিম স্কেনৰ তাৰিখ',
    noRecentScans: 'কোনো শেহতীয়া স্কেন নাই',
    latestDrug: 'শেহতীয়া ঔষধ',
    verifiedAI: 'এআই প্ৰমাণিত',
    scanNewMedicine: 'নতুন ঔষধ স্কেন কৰক',
    scanNewDesc: 'নিৰাপদ মাত্ৰা আৰু ব্যৱহাৰৰ বাবে কেমেৰা ধৰক',
    openScanner: 'স্কেনাৰ খোলক',
    myCabinetTitle: 'মোৰ ঔষধৰ বাকচ',
    myCabinetDesc: 'ৰোগ অনুসৰি সজোৱা ঔষধসমূহ চাওক',
    openCabinet: 'বাকচ খোলক',
    reportsRxTitle: 'প্ৰতিবেদন আৰু প্ৰেছক্ৰিপশ্বন এআই',
    reportsRxDesc: 'প্ৰেছক্ৰিপশ্বন ডিজিটাইজ কৰক বা পৰীক্ষা কৰক',
    openReports: 'প্ৰতিবেদন খোলক',
    recentScans: 'শেহতীয়া ঔষধ স্কেন',
    viewAllHistory: 'সকলো ইতিহাস চাওক',
    noScansYet: 'কোনো স্কেন নাই। আৰম্ভ কৰিবলৈ স্কেনাৰ টিপক!',

    cognitiveTitle: 'স্মৃতিচর্চা আৰু সহায়',
    cognitiveSubtitle: 'অফলাইন স্মৃতিশক্তি খেল আৰু স্বয়ংক্ৰিয় সোঁৱৰণি',
    offlineActive: 'অফলাইন সক্ৰিয়',
    reminiscenceMatchCard: 'স্মৃতি খেল',
    reminiscenceMatchDesc: '১০টা কঠিন স্তৰৰ স্মৰণ খেল।',
    launchGame: 'খেল আৰম্ভ কৰক',
    dailyVoiceRemindersCard: 'দৈনিক ভইচ সোঁৱৰণি',
    dailyVoiceRemindersDesc: 'পানী খাবলৈ আৰু ঔষধৰ বাবে মাত মাতি সোঁৱৰাই দিয়ে।',
    viewSchedule: 'সময়সূচী চাওক',
    caregiverHubCard: 'যত্নশীল ব্যক্তিৰ হাব',
    caregiverHubDesc: 'স্মৃতিশক্তিৰ গ্রাফ আৰু সতৰ্কবাৰ্তা।',
    openAnalytics: 'বিশ্লেষণ খোলক',
    sanjeevaniVoiceAICard: 'সঞ্জীৱনী ভইচ এআই',
    sanjeevaniVoiceAIDesc: 'অসমীয়াত কথা পাতক আৰু ঔষধৰ বিষয়ে জানক।',
    talkWithVoiceAI: 'ভইচত কথা পাতক',
    voiceTherapistCard: 'ডাঃ অনন্যা — ভইচ থেৰাপিষ্ট',
    voiceTherapistDesc: 'মনৰ শান্তি আৰু আপোন কথাৰ বাবে থেৰাপী কক্ষ।',
    enterTherapyRoom: 'থেৰাপী কক্ষত প্ৰৱেশ কৰক',

    drinkWater: '✓ মই পানী খালোঁ',
    takeMedicine: '✓ মই ঔষধ খালোঁ',
    remind10Min: '১০ মিনিট পিছত মনত পেলাওক',
    listenAgain: 'পুনৰ শুনক',
    hydrationAlert: 'পানী খোৱাৰ সময় হৈছে',
    medicationAlert: 'ঔষধ খোৱাৰ সময় হৈছে',

    positionMedicine: 'ঔষধৰ লেবেল ইয়াত ৰাখক',
    captureAnalyze: 'ফটো লওক আৰু পৰীক্ষা কৰক',
    uploadFile: 'ফাইল আপলোড কৰক',
    switchCam: 'কেমেৰা সলাওক',
    retakeScan: 'পুনৰ স্কেন কৰক',
    analyzing: 'ঔষধ পৰীক্ষা কৰা হৈ আছে...',
    analyzingDesc: 'উপাদান আৰু সুৰক্ষাৰ নিয়ম পঢ়া হৈছে',
    flashcards: 'ফ্লেশকাৰ্ড',
    singleColumn: 'একক স্তম্ভ',
    showAllCards: 'সকলো কাৰ্ড দেখুৱাওক',
    carouselView: 'কাৰ্ড স্লাইডাৰ',
    previousCard: 'পূৰ্বৱৰ্তী কাৰ্ড',
    nextCard: 'পৰৱৰ্তী কাৰ্ড',
    cardXofY: 'কাৰ্ড {x} / {y}',
    primaryUse: 'প্ৰধান ব্যৱহাৰ আৰু লক্ষণ',
    activeIngredients: 'সক্ৰিয় উপাদান (Salts)',
    dosageInstructions: 'মাত্ৰা আৰু নিয়মাবলী',
    warnings: 'গুৰুত্বপূৰ্ণ সাৱধানবাণী',
    sideEffects: 'পাৰ্শ্বক্ৰিয়া',
    ncbiRecord: 'NCBI ৰেকৰ্ড',
    aiPharmacist: 'এআই ফাৰ্মাচিষ্ট প্ৰশ্নোত্তৰ',
    askPharmacist: 'এই ঔষধৰ বিষয়ে কিবা সোধক...',
    askBtn: 'সোধক',
    disclaimer: '* তথ্য: এয়া কেৱল সহায়ক ব্যৱস্থা। চিকিৎসকৰ পৰামৰ্শ লওক।',

    cabinetHeader: 'মোৰ ঔষধৰ বাকচ',
    cabinetSubtitle: 'আপোনাৰ ঔষধসমূহ বিভাগ অনুসৰি সজাই ৰখা হৈছে।',
    totalCabinetMeds: 'মুঠ ঔষধ',
    activeDiseaseCats: 'বিভাগৰ সংখ্যা',
    orgStatus: 'অৱস্থা',
    allSorted: '১০০% সজোৱা হৈছে',
    aiTaxonomy: 'চিকিৎসা শ্ৰেণীবিভাজন',
    searchPlaceholder: 'ঔষধ বা বেমাৰ বিচাৰক…',
    allDiseases: 'সকলো বিভাগ',
    medicinesCount: '{count}টা ঔষধ',
    addedOn: '{date} তাৰিখে যোগ কৰা হ\'ল',
    viewDetails: 'বিৱৰণ চাওক',
    emptyCabinet: 'বাকচ খালী হৈ আছে',
    emptyCabinetDesc: 'ঔষধ স্কেন কৰি বাকচত ভৰাওক।',
    scanFirstMed: 'প্ৰথম ঔষধ স্কেন কৰক',

    reportsHeader: 'প্ৰতিবেদন আৰু প্ৰেছক্ৰিপশ্বন এআই',
    reportsSubtitle: 'ৰক্ত পৰীক্ষা আৰু প্ৰেছক্ৰিপশ্বন নিৰীক্ষণ কৰি সুৰক্ষা নিশ্চিত কৰক।',
    dualAuditTab: '⚡ দ্বৈত নিৰীক্ষণ (লেব + প্ৰেছক্ৰিপশ্বন)',
    rxDigitizerTab: 'প্ৰেছক্ৰিপশ্বন ৰিডাৰ',
    labReportTab: 'লেব প্ৰতিবেদন বিশ্লেষক',
    uploadBothDocs: 'দুয়োটা নথি আপলোড কৰক',
    dualAuditDesc: 'ঔষধসমূহ শৰীৰৰ বাবে নিৰাপদ নে নহয় এআই পৰীক্ষা কৰে।',
    doc1Lab: 'নথি ১: ৰক্ত পৰীক্ষা প্ৰতিবেদন',
    clickUploadLab: 'প্ৰতিবেদন বাছক',
    doc2Rx: 'নথি ২: প্ৰেছক্ৰিপশ্বন',
    clickUploadRx: 'প্ৰেছক্ৰিপশ্বন বাছক',
    runDualAuditBtn: '৩৬০° দ্বৈত নিৰীক্ষণ আৰম্ভ কৰক',
    uploadRxTitle: 'প্ৰেছক্ৰিপশ্বন আপলোড কৰক',
    rxUploadDesc: 'হাতে লিখা কাগজ সমৰ্থিত',
    digitizeRxBtn: 'ঔষধৰ তালিকা উলিয়াওক',
    uploadLabTitle: 'ৰক্ত পৰীক্ষাৰ প্ৰতিবেদন',
    labUploadDesc: 'চিবিচি, লিপিড ইত্যাদি',
    analyzeLabBtn: 'প্ৰতিবেদন পৰীক্ষা কৰক',

    caregiverHeader: 'যত্নশীল ব্যক্তিৰ হাব',
    caregiverSubtitle: 'স্মৃতিশক্তিৰ খতিয়ান আৰু যত্ন নিৰ্দেশনা।',
    trailing7Days: 'যোৱা ৭ দিন',
    trailing30Days: 'যোৱা ৩০ দিন',
    manualSync: 'তথ্য সমন্বয় কৰক',
    syncingStatus: 'সমন্বয় হৈ আছে...',
    onlineMode: 'সংযোগ কৰা হৈছে',
    offlineStore: 'অফলাইন সক্ৰিয়',
    avgAccuracy: 'স্মৰণ নিখুঁততা',
    hesitationLatency: 'ভাবাৰ সময়',
    hydrationCompliance: 'পানী খোৱাৰ হাৰ',
    medicationCompliance: 'ঔষধ খোৱাৰ হাৰ',
    trendlineTitle: 'নিখুঁততাৰ নক্সা',
    anomalyTitle: 'অৱনতিৰ সতৰ্কবাণী',
    anomalyNormal: 'স্মৃতিশক্তি সুস্থিৰ আছে।',
    anomalyWarning: 'সাৱধান: মানসিক খেলি-মেলি লক্ষ্য কৰা হৈছে।',

    morning: 'ৰাতিপুৱা',
    afternoon: 'দুপৰীয়া',
    night: 'ৰাতি',
    duration: 'ম্যাদ',
    timing: 'সময়',
    saveToCabinet: 'বাকচত সাঁচক ({count})',
    selectedOf: 'নিৰ্বাচিত: {x} / {y}'
  },

  // ──────────────────────────── MARATHI (मराठी) ────────────────────────────
  mr: {
    appName: 'Smriti Setu',
    tagline: 'डिमेंशिया आणि स्मरणशक्ती काळजी सेवा',
    home: 'होम',
    scanner: 'औषध स्कॅनर',
    reportsRx: 'अहवाल आणि प्रिस्क्रिप्शन',
    cabinet: 'माझी औषध पेटी',
    cognitiveGames: 'स्मरण खेळ',
    memoryReminders: 'दैनिक स्मरणपत्रे',
    caregiverAnalytics: 'केअरगिव्हर हब',
    history: 'इतिहास',
    profile: 'प्रोफाइल',
    logout: 'लॉगआउट',
    signIn: 'साइन इन करा',
    signUp: 'साइन अप करा',
    register: 'नोंदणी करा',
    email: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    fullName: 'पूर्ण नाव',
    alreadyAccount: 'आधीच खाते आहे का?',
    noAccount: 'खाते नाही? आता नोंदणी करा',
    selectLanguage: 'भाषा निवडा',
    listenAudio: 'ऐका (ऑडिओ)',
    speaking: 'वाचत आहे...',
    voiceTherapist: 'व्हॉइस थेरपिस्ट',
    voiceAI: 'व्हॉइस एआय',

    goodMorning: 'शुभ सकाळ',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    dashboardSubtitle: 'तुमच्या औषध स्कॅनिंग आणि आरोग्याचा सारांश.',
    totalScans: 'एकूण स्कॅन',
    allTimeScans: 'विश्लेषण केलेली औषधे',
    lastScanDate: 'शेवटची स्कॅन तारीख',
    noRecentScans: 'कोणतेही अलीकडील स्कॅन नाही',
    latestDrug: 'नवीनतम औषध',
    verifiedAI: 'एआय द्वारे पडताळणी',
    scanNewMedicine: 'नवीन औषध स्कॅन करा',
    scanNewDesc: 'डोस आणि सुरक्षितता मार्गदर्शनासाठी औषधाच्या पाकिटावर कॅमेरा धरा',
    openScanner: 'औषध स्कॅनर उघडा',
    myCabinetTitle: 'माझी औषध पेटी',
    myCabinetDesc: 'आजारांनुसार वर्गीकरण केलेली औषधे पाहा',
    openCabinet: 'पेटी उघडा',
    reportsRxTitle: 'अहवाल आणि प्रिस्क्रिप्शन एआय',
    reportsRxDesc: 'डॉक्टरांची चिठ्ठी डिजिटाइझ करा किंवा लॅब अहवाल तपासा',
    openReports: 'अहवाल उघडा',
    recentScans: 'अलीकडील औषध स्कॅन',
    viewAllHistory: 'संपूर्ण इतिहास पाहा',
    noScansYet: 'अद्याप कोणतेही स्कॅन नाही. सुरू करण्यासाठी स्कॅनर दाबा!',

    cognitiveTitle: 'स्मरण चिकित्सा व मदत',
    cognitiveSubtitle: 'ऑफलाइन स्मरणशक्ती खेळ आणि स्वयंचलित ऑडिओ स्मरणपत्रे',
    offlineActive: 'ऑफलाइन सक्रिय',
    reminiscenceMatchCard: 'स्मरण जुळवणी खेळ',
    reminiscenceMatchDesc: 'भारतीय संस्कृतीवर आधारित १० आव्हानात्मक स्तरांचा स्मरण खेळ.',
    launchGame: 'खेळ सुरू करा',
    dailyVoiceRemindersCard: 'दैनिक व्हॉइस स्मरणपत्रे',
    dailyVoiceRemindersDesc: 'पाणी पिण्यासाठी आणि वेळेवर औषधे घेण्यासाठी स्थानिक आवाजात सूचना.',
    viewSchedule: 'वेळापत्रक पाहा',
    caregiverHubCard: 'केअरगिव्हर हब',
    caregiverHubDesc: 'स्मरणशक्तीचा आलेख आणि घसरण झाल्यास तात्काळ इशारा.',
    openAnalytics: 'अॅनालिटिक्स उघडा',
    sanjeevaniVoiceAICard: 'संजीवनी व्हॉइस एआय',
    sanjeevaniVoiceAIDesc: 'मराठीत बोला आणि औषध व आरोग्याबद्दल झटपट उत्तरे मिळवा.',
    talkWithVoiceAI: 'आवाजाने बोला',
    voiceTherapistCard: 'डॉ. अनन्या — व्हॉइस थेरपिस्ट',
    voiceTherapistDesc: 'चिंता कमी करण्यासाठी, शांत राहण्यासाठी आणि आत्मीयतेने बोलण्यासाठी कक्ष.',
    enterTherapyRoom: 'थेरपी रूममध्ये जा',

    drinkWater: '✓ मी पाणी प्यायलो',
    takeMedicine: '✓ मी औषध घेतले',
    remind10Min: '१० मिनिटांनी आठवण करा',
    listenAgain: 'आवाज पुन्हा ऐका',
    hydrationAlert: 'पाणी पिण्याची वेळ झाली आहे',
    medicationAlert: 'औषध घेण्याची वेळ झाली आहे',

    positionMedicine: 'औषधाचे लेबल येथे ठेवा',
    captureAnalyze: 'फोटो काढा आणि तपासा',
    uploadFile: 'फाइल अपलोड करा',
    switchCam: 'कॅमेरा बदला',
    retakeScan: 'पुन्हा स्कॅन करा',
    analyzing: 'औषधाचे विश्लेषण चालू आहे...',
    analyzingDesc: 'घटक, डोस आणि सुरक्षिततेचे नियम वाचत आहे',
    flashcards: 'फ्लॅशकार्ड्स',
    singleColumn: 'एकच स्तंभ',
    showAllCards: 'सर्व कार्ड दाखवा',
    carouselView: 'कार्ड स्लायडर',
    previousCard: 'मागील कार्ड',
    nextCard: 'पुढील कार्ड',
    cardXofY: 'कार्ड {x} / {y}',
    primaryUse: 'प्रमुख उपयोग आणि संकेत',
    activeIngredients: 'सक्रिय घटक (Salts)',
    dosageInstructions: 'डोस आणि सेवनाचे नियम',
    warnings: 'महत्त्वाच्या सूचना आणि इशारे',
    sideEffects: 'संभाव्य दुष्परिणाम',
    ncbiRecord: 'NCBI रेकॉर्ड',
    aiPharmacist: 'एआय फार्मासिस्ट प्रश्नोत्तरे',
    askPharmacist: 'या औषधाबद्दल काहीही विचारा...',
    askBtn: 'विचारा',
    disclaimer: '* सूचना: हे केवळ सहाय्यक साधन आहे. डॉक्टरांचा सल्ला अवश्य घ्या.',

    cabinetHeader: 'माझी औषध पेटी',
    cabinetSubtitle: 'तुमची सर्व औषधे आजारांनुसार व्यवस्थित ठेवली आहेत.',
    totalCabinetMeds: 'एकूण औषधे',
    activeDiseaseCats: 'विभागांची संख्या',
    orgStatus: 'स्थिती',
    allSorted: '१००% व्यवस्थित',
    aiTaxonomy: 'क्लिनिकल वर्गीकरण',
    searchPlaceholder: 'औषध किंवा आजार शोधा…',
    allDiseases: 'सर्व आजार',
    medicinesCount: '{count} औषधे',
    addedOn: '{date} रोजी जोडले',
    viewDetails: 'तपशील पाहा',
    emptyCabinet: 'औषध पेटी रिकामी आहे',
    emptyCabinetDesc: 'पाकीट स्कॅन करून आपल्या पेटीत औषधे जोडा.',
    scanFirstMed: 'पहिले औषध स्कॅन करा',

    reportsHeader: 'अहवाल आणि प्रिस्क्रिप्शन एआय',
    reportsSubtitle: 'रक्त तपासणी आणि प्रिस्क्रिप्शनचे ३६०° ऑडिट करून सुरक्षितता तपासा.',
    dualAuditTab: '⚡ दुहेरी ऑडिट (लॅब + प्रिस्क्रिप्शन)',
    rxDigitizerTab: 'प्रिस्क्रिप्शन रीडर',
    labReportTab: 'लॅब अहवाल विश्लेषक',
    uploadBothDocs: 'दोन्ही दस्तऐवज अपलोड करा',
    dualAuditDesc: 'औषधे शरीरासाठी सुरक्षित आहेत का हे एआय तपासते.',
    doc1Lab: 'दस्तऐवज १: रक्त अहवाल',
    clickUploadLab: 'अहवाल निवडा',
    doc2Rx: 'दस्तऐवज २: डॉक्टरांची चिठ्ठी',
    clickUploadRx: 'चिठ्ठी निवडा',
    runDualAuditBtn: '३६০° दुहेरी सुरक्षा ऑडिट सुरू करा',
    uploadRxTitle: 'प्रिस्क्रिप्शन अपलोड करा',
    rxUploadDesc: 'हस्तलिखित आणि डिजिटल चिठ्ठ्या समर्थित',
    digitizeRxBtn: 'औषधांची यादी काढा',
    uploadLabTitle: 'रक्त तपासणी अहवाल',
    labUploadDesc: 'सीबीसी, लिपिड प्रोफाइल इत्यादी',
    analyzeLabBtn: 'अहवाल तपासा',

    caregiverHeader: 'केअरगिव्हर हब',
    caregiverSubtitle: 'स्मरणशक्ती प्रगती आणि आरोग्य निरीक्षण.',
    trailing7Days: 'मागील ७ दिवस',
    trailing30Days: 'मागील ३० दिवस',
    manualSync: 'डेटा सिंक करा',
    syncingStatus: 'सिंक होत आहे...',
    onlineMode: 'ऑनलाइन जोडलेले',
    offlineStore: 'ऑफलाइन सक्रिय',
    avgAccuracy: 'स्मरण अचूकता',
    hesitationLatency: 'विचार करण्याचा वेळ',
    hydrationCompliance: 'पाणी पिण्याचे प्रमाण',
    medicationCompliance: 'औषध अनुपालन प्रमाण',
    trendlineTitle: 'अचूकता आलेख',
    anomalyTitle: 'घसरण सतर्कता',
    anomalyNormal: 'स्मरणशक्ती स्थिर आहे.',
    anomalyWarning: 'इशारा: कामगिरीत घसरण झाली आहे. काळजी घ्या.',

    morning: 'सकाळ',
    afternoon: 'दुपार',
    night: 'रात्र',
    duration: 'कालावधी',
    timing: 'वेळ',
    saveToCabinet: 'पेटीत जतन करा ({count})',
    selectedOf: 'निवडले: {x} / {y}'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('pharmavision_lang') || 'en';
  });

  const applyDomLanguage = (newLang) => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = newLang;
      // Set language class on body for responsive font adjustments
      const currentClasses = document.body.className.split(' ').filter(c => !c.startsWith('lang-'));
      currentClasses.push(`lang-${newLang}`);
      document.body.className = currentClasses.join(' ');
    }
  };

  const changeLanguage = (newLang) => {
    try {
      setLang(newLang);
      localStorage.setItem('pharmavision_lang', newLang);
      applyDomLanguage(newLang);

      // Trigger full DOM live translation engine & cookies
      liveTranslationService.triggerDomTranslation(newLang);

      // Dispatch custom events
      window.dispatchEvent(new CustomEvent('languageChange', { detail: { lang: newLang } }));
      window.dispatchEvent(new Event('storage'));
    } catch (err) {
      console.warn('Language update error:', err);
    }

    // Unconditionally reload page immediately
    if (typeof window !== 'undefined') {
      window.location.reload();
    }
  };

  useEffect(() => {
    const saved = localStorage.getItem('pharmavision_lang') || 'en';
    applyDomLanguage(saved);
    if (saved !== 'en') {
      setTimeout(() => {
        liveTranslationService.triggerDomTranslation(saved);
      }, 400);
    }
  }, []);

  const t = (key, params = {}) => {
    if (key === 'appName') return 'Smriti Setu';
    let str = translations[lang]?.[key] || translations['en']?.[key] || key;
    if (typeof str === 'string') {
      Object.keys(params).forEach(p => {
        str = str.replace(new RegExp(`\\{${p}\\}`, 'g'), params[p]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
